sudo: false
language: ruby
cache:
  bundler: true
rvm:
  - "2.2.6"
  - "2.3.3"
gemfiles:
  - Gemfile
  - test/gemfiles/Gemfile-Rails-4.2
env:
  - ADAPTER=mysql2
  - ADAPTER=postgresql
before_script:
  - mysql -e "create database bigint_test;"
  - psql -c "create database bigint_test;" -U postgres
